%% plot chattering phenomenon
error1 = Err1.signals.values;
error2 = Err.signals.values;
u = nonlinearU.signals.values * 1e9;
accSignal = acc.signals.values;
error = [error1,error2]*1e9;
ratio = max(max(abs(error))) / max(accSignal);
time = acc.time;
figure;
subplot(2,1,1);
h = plot(time,error,'linewidth',1);
h(2).Color = [0.9290    0.6940    0.1250];
h(1).DisplayName = 'linear feedback';
h(2).DisplayName = 'PBVGC';
hold on;
h = plot(time,ratio * accSignal,'linewidth',1);
h.Color = 'r';
h.DisplayName = 'scaled acc';
xlim([0,max(time)]);
ylabel('error (nm)');
legend show;
set(gca,'fontsize',13);
subplot(2,1,2);
h = plot(time,u,'linewidth',1);
h.Color = [0.9290    0.6940    0.1250];
xlim([0,max(time)]);
ylabel('u (nm)');
xlabel('time (s)');
set(gca,'fontsize',13);
%% plot overcome chattering with dwell time
error1 = Err1.signals.values;
error2 = Err.signals.values;
u = nonlinearU.signals.values * 1e9;
accSignal = acc.signals.values;
error = [error1,error2]*1e9;
ratio = max(max(abs(error))) / max(accSignal);
time = acc.time;
figure;
h = plot(time,error,'linewidth',1);
h(2).Color = [0.9290    0.6940    0.1250];
h(1).DisplayName = 'PBVGC';
h(2).DisplayName = 'PBVGC with dwell time';
hold on;
h = plot(time,ratio * accSignal,'linewidth',1);
h.Color = 'r';
h.DisplayName = 'scaled acc';
xlim([0,max(time)]);
ylabel('error (nm)');
legend show;
set(gca,'fontsize',13);
xlabel('time (s)');
%% plot fast switching
error1 = Err1.signals.values;
error2 = Err.signals.values;
u = nonlinearU.signals.values * 1e9;
accSignal = acc.signals.values;
error = [error1,error2]*1e9;
ratio = max(max(abs(error))) / max(accSignal);
time = acc.time;
figure;
h = plot(time,error,'linewidth',1);
h(2).Color = [0.9290    0.6940    0.1250];
h(1).DisplayName = 'linear feedback';
h(2).DisplayName = 'PBVGC with dwell time';
hold on;
% h = plot(time,ratio * accSignal,'linewidth',1);
% h.Color = 'r';
% h.DisplayName = 'scaled acc';
xlim([0.073,0.16]);
ylabel('error (nm)');
legend show;
set(gca,'fontsize',13);
xlabel('time (s)');